server:
  port: 8080
  servlet:
    context-path: /worklite
spring:
  application:
    name: worklite

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: root
    url: jdbc:mysql://127.0.0.1:3306/worklite?serverTimezone=GMT%2B8
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
  #======== redis =======

  redis:
    database: 0
    host: 47.98.184.195
    port: 6379
    password:
    jedis:
      pool:
        enabled: true
        max-active: 8
        max-wait: -1
        max-idle: 8
        min-idle: 0
    timeout: 1000
    connect-timeout: 5000

# ===== 自定义swagger配置 ===== #
swagger:
    enable: true
    application-name: ${spring.application.name}/私有工作站
    application-version: 1.0
    application-description: springfox swagger 3.0
    try-host: http://localhost:${server.port}/${spring.application.name}
    access:
      #设置允许访问的ip地址白名单,以英文逗号分隔
      iplist: 127.0.0.1

#springfox:
#  documentation:
#    swagger-ui:
#      enabled: true
#      base-url: /swagger


